### ISSUE TITLE
MozCoffee Website Design

### ISSUE THREAD

**Issue by yofiesetiawan** [mozilla/OpenDesign#28] opened 2016-02-03 07:08 UTC
There was an idea to create a website regarding our popular event around the world, the MozCoffee. The idea is to put information about what is mozcoffee and how if you want to run one in your places. And this site can also give some preview of pictures embeded from Flickr.

Anyone have an idea about the moz.coffee domain status right now?

**Comment by ecwebservices** [comment] 2016-02-08 21:19
moz.coffee is currently not available.

**Comment by yofiesetiawan** [comment] 2016-02-09 02:10
Thank you @ecwebservices

**Comment by ioana-chiorean** [comment] 2016-02-09 13:25
Kensie - Majken Connors had website close to this name. Let me ask her.

**Comment by ioana-chiorean** [comment] 2016-02-09 15:27
Here is the thread: https://discourse.mozilla-community.org/t/moz-coffee-domain/1733

**Comment by elioqoshi** [comment] 2016-02-11 14:41
@yofiesetiawan would you be up to design the website for this?

**Comment by yofiesetiawan** [comment] 2016-02-11 16:38
@elioqoshi i'm thinking of welcoming anyone who wants to pitch their designs?

**Comment by elioqoshi** [comment] 2016-02-11 19:17
Okay, @all feel free to pitch with designs!

**Comment by seeam** [comment] 2016-02-12 01:35
Hey, I may give it a try but after a few days. But @yofiesetiawan can you give me some brief that what type of content you want to present in the site?

**Comment by yofiesetiawan** [comment] 2016-02-12 03:47
@seeam the idea is to share short information about MozCoffee activity, and how people can create their own MozCoffee in their country. Then showcasing pictures of MozCoffee activities... This could be 1 page site...

**Comment by elioqoshi** [comment] 2016-02-12 06:59
Maybe we can start with wireframes first?

**Comment by seeam** [comment] 2016-02-12 15:32
@yofiesetiawan can you give some link/context about how can people arrange their own MozCoffe? Cause I'm not a reps and not aware of the event approving / proposing procedure.

**Comment by yofiesetiawan** [comment] 2016-02-12 16:03
@seeam i'm not sure if i make a right definition about mozcoffee. But usually mozcoffee events can be sponsored by Mozilla because you have a mozilla rep helping for budget and swag request. But i think anyone who want to just create a meetup event and talking about mozilla, we can call that as mozcoffee already? How do you think? @elioqoshi

**Comment by seeam** [comment] 2016-02-12 17:07
I tried to create a wireframe and ended up with this, usually I don't pitch my wireframe (cause it's difficult for others to understand). Anyway, basically the site will have following segments:

- Tabzilla.
- The MozCoffee logo at the top.
- **A hero image**, we may chose it from past events. Also an attractive title like _Discuss the **Moz**illa Mission over a cup of **Coffe**._ Then we may put some introductory text.
- Then a **timer** (see below the tabzilla), counting of the next event. We may get this data from reps portal. 
- Then some tabs to elaborate what or why it is. The tab with a icon, a title and some text.
- Then we may show how to arrange, criteria and budget. (I just checked that those are available on the wiki page). I want to arrange this segment like [FSA landing page](https://www.mozilla.org/en-US/contribute/studentambassadors/). I really liked their hierarchy of content arrangment.
- Now we can show some photos from past events, blogs and crawl data from twitter with MozCoffe hashtag.
- The basic and commong Mozilla footer.


So what is your thought, @yofiesetiawan and @elioqoshi? 
![photo351612214017370532](https://cloud.githubusercontent.com/assets/7550283/13013952/c0217ffa-d1db-11e5-99c0-a0ee0dca9c8

**Comment by yofiesetiawan** [comment] 2016-02-12 19:00
Really nice job @seeam i think we can go with that...

**Comment by seeam** [comment] 2016-02-16 05:20
I have changed the wireframe a bit, here is a high fidelity wireframe created in Photoshop. What do you think?
![bootstrap3-1170px](https://cloud.githubusercontent.com/assets/7550283/13067849/229fdf58-d49f-11e5-9265-99ab56982728.jpg)

**Comment by yofiesetiawan** [comment] 2016-02-16 05:35
Hi @seeam it looks great. However, what about we change the blue bg color to coffee image as background, but adding some dark shade on the image?

And maybe separate those 3 icons from the blue background?
How do others think? @elioqoshi 

Anyway @ioana-chiorean how is the news about the domain?

**Comment by seeam** [comment] 2016-02-16 05:44
Adding the 3 icons inside blue background was intentional. If you think about visual hierarchy, the page is divided into 4 sections.
1. Summary: Which is inside blue background and at the top. Invitation for creating someone's own event and what to do in a nutshell.
2. Instructions.
3. Past Experience
4. Footer.
That's why I keep those three tabs inside blue background.

And I am little confused about your suggestion for background. Do you thinking about coffee color as background?

**Comment by yofiesetiawan** [comment] 2016-02-16 05:46
Well nice explaination.. Can you share the psd file? So i can try to modify the layout? @seeam

**Comment by seeam** [comment] 2016-02-16 05:50
Sure, here is the PSD.
[MozCoffee Landing Page.zip](https://github.com/mozilla/Community-Design/files/131951/MozCoffee.Landing.Page.zip)

**Comment by yofiesetiawan** [comment] 2016-02-16 06:04
I mean something like this.. @seeam anyway we need someone to help to code...
![bootstrap3-1170px](https://cloud.githubusercontent.com/assets/2810823/13068413/c03eedf4-d4ad-11e5-8c81-e3b154d91fbb.jpg)

**Comment by seeam** [comment] 2016-02-16 06:12
Oh, but this image looks like we are opening a coffee business! :smile: 
How about this, which symbolize community and coffee both? 
![pitch-2](https://cloud.githubusercontent.com/assets/7550283/13068514/445f97da-d4a6-11e5-9426-f4a8c97ce282.jpg)

**Comment by yofiesetiawan** [comment] 2016-02-16 06:13
i like your idea @seeam

**Comment by seeam** [comment] 2016-02-16 06:15
By the I have forgot to mention that these icons I have used is from http://www.flaticon.com under CC 3.0 license.

**Comment by anistuhin** [comment] 2016-02-16 12:06
great things coming up, I see :) I can help coding it as soon you guys are done with selecting the final one @yofiesetiawan

**Comment by yofiesetiawan** [comment] 2016-02-19 01:51
@ioana-chiorean do you already get the status of the domain? 
@elioqoshi have any comments regarding last design draft?

**Comment by elioqoshi** [comment] 2016-02-20 00:14
I have, but currently preparing for my last exam so need to comment later.
Let's put the proper logo on the header (fully in white) and the 3 icons in the middle to look more like the Mozilla ones on www.mozilla.org

The boxes should have different background colors, instead of white maybe?
Looking great so far!
@seeam can you share the PSD?

**Comment by seeam** [comment] 2016-02-20 14:46
Here it is.
[MozCoffee Landing Page (2).zip](https://github.com/mozilla/Community-Design/files/139162/MozCoffee.Landing.Page.2.zip)

**Comment by yofiesetiawan** [comment] 2016-02-24 16:58
![mozcoffee-seeam-modified-yofie](https://cloud.githubusercontent.com/assets/2810823/13293432/3feb8012-db52-11e5-9aa6-0406e476d76b.jpg)
proposing revision.. anyway... who should be the one to decide which design is chosen? @elioqoshi 

https://dl.dropboxusercontent.com/u/4450713/mozilla/mozcoffee-seeam-modified-yofie.zip

**Comment by seeam** [comment] 2016-02-24 17:02
@yofiesetiawan if you are planning to do this change the shadow color of mug and tabzilla.

**Comment by mijanurrahman** [comment] 2016-02-26 18:50
Great thing (y) and Great design @seeam :D Love it

**Comment by elioqoshi** [comment] 2016-03-06 13:03
@yofiesetiawan can we make the 3 circles in different colors? Also, you can find the logo here:
https://wiki.mozilla.org/ReMo/SOPs/MozCoffee

Furthermore, maybe a very transparent background image behind the brown background?

@yofiesetiawan @seeam please post it on Discourse and/or Reps General after it's finished so we can get people's thoughts to choose the most popular choice.

**Comment by elioqoshi** [comment] 2016-03-06 13:04
P.S: I personally prefer Yofie's variant (with the changes I suggested also)

**Comment by brutalcrozt** [comment] 2016-03-16 05:10
may i ask why developer needed here?

**Comment by elioqoshi** [comment] 2016-03-16 09:06
Someone needs to code it ;)
@yofiesetiawan where are we with this?

**Comment by yofiesetiawan** [comment] 2016-03-16 10:02
@elioqoshi i have difficulty to find the status of the domain name... if anyone can help to execute to code the latest psd file from @seeam that would be great..

**Comment by elioqoshi** [comment] 2016-03-16 10:06
Which is the domain name, what needs to be done yet? Do we have any employees who can help out here? @LucyeoH

**Comment by parag9d** [comment] 2016-03-16 11:22
Is the design final? I like the hero image of Seeam's work, it shows community discussions.
But some work needs to be done on the icons and the footer. I would like to help with that and also with the responsive versions for tablet and mobile, if needed.

**Comment by yofiesetiawan** [comment] 2016-03-17 07:35
Hi @seeam, can you work together with @parag9d to finish this?

**Comment by parag9d** [comment] 2016-03-17 14:38
@elioqoshi @yofiesetiawan I had one doubt, I had been going through the Sandstone page(https://www.mozilla.org/en-US/styleguide/websites/sandstone/grids/) for the styleguide, it says that the width for desktop is 990px. 
This is followed for all the event pages like https://reps.mozilla.org/e/fossasia-2016/ but in the Mozilla homepage, only the top nav including the tabzilla falls under 990 px, but the rest goes out.

So, in Mozcoffee page, should the tabzilla and the MozCoffee logo stay inside the 990px? In @seeam's psd it doesn't.

**Comment by seeam** [comment] 2016-03-17 14:58
@yofiesetiawan I have final exam's ahead may be I can't give much time here. @parag9d I haven't followed sandstone grids, in my opinion it's a bit dated as most people uses bigger screen these days. So I have used bootstrap 1170px grids.

**Comment by parag9d** [comment] 2016-03-18 17:44
![mozcoffee landing page-1](https://cloud.githubusercontent.com/assets/6411097/13886861/0d33f1bc-ed5f-11e5-8c6a-04b508853da9.png)

**Comment by elioqoshi** [comment] 2016-03-19 08:50
Love this! @yofiesetiawan what do you think?

**Comment by yofiesetiawan** [comment] 2016-03-19 17:02
@elioqoshi @seeam i like this, can someone please help to start to code with this?

**Comment by brutalcrozt** [comment] 2016-03-20 04:28
i wouldn't able to give full time due to some school test, who lead the development?

**Comment by yofiesetiawan** [comment] 2016-03-20 05:02
@brutalcrozt its okay you can help during your free time... i will help to lead this project.. please note i'm not good with github :P

**Comment by anistuhin** [comment] 2016-03-20 06:53
I can help with coding. @yofiesetiawan So we are all set to go on coding??

**Comment by brutalcrozt** [comment] 2016-03-20 09:27
@yofiesetiawan okay sir, what are our tools?

**Comment by yofiesetiawan** [comment] 2016-03-20 10:47
@anistuhin @brutalcrozt actually usually i work with start create a new account with cpanel. but that won't be right for our open source community, right? usually we start development on github? how do you guys do that as developers? i think you guys know better? then after we finished with the development, we can start to move it to proper server to make it online?

**Comment by anistuhin** [comment] 2016-03-20 15:09
Yes, we should go with GitHub first. I have done few Mozilla projects that way as well. After we are done with development, we will then transfer it to live server and the repo can still be used for tracking and solving issues and bugs :) I am starting it from tomorrow :) Will post the GitHub repo link here then.

**Comment by yofiesetiawan** [comment] 2016-03-20 17:38
Thanks @anistuhin for assigning as developer for this project. @brutalcrozt please help to keep an eye on this...

**Comment by anistuhin** [comment] 2016-03-25 13:04
@parag9d could you please share the PSD here and also update with the small screens when you are done :)

**Comment by parag9d** [comment] 2016-03-26 04:29
Hi @anistuhin You can access the files here: https://drive.google.com/file/d/0B6Mo2oHOR0f0UUVhNnpPLWg2aGs/view?usp=sharing

Please switch-on the grid layer (the topmost layer). You will get the idea how the components are arranged. Thanks.

**Comment by brutalcrozt** [comment] 2016-03-26 04:55
what is our next step?

**Comment by parag9d** [comment] 2016-03-29 07:28
![responsive](https://cloud.githubusercontent.com/assets/6411097/14100830/ea3cbab6-f5ad-11e5-947d-21280344abf5.png)
 See the full project on https://dribbble.com/ParagNandi/projects/364315-MozCoffee

**Comment by Subway19** [comment] 2016-03-31 18:49
I like this and interested in contribution here; i can help with coding, Can someone tell me where is the code hosted and open for contribution if the webpage is still being developed? Thanks.

**Comment by Ryuno-Ki** [comment] 2016-04-01 19:58
@anistuhin wanted to provide a GitHub link.

I prefer https://github.com/mozilla/Community-Design/issues/28#issuecomment-198467226 the most albeit the white text may be hard to read on the blue background of the hero image (there are people with cognitive disablities out there). On the other hand a plain background like https://github.com/mozilla/Community-Design/issues/28#issuecomment-188352617 looks somewhat boring. Maybe it's sufficient to decrease the opacity ("watermark") of the image.

**Comment by anistuhin** [comment] 2016-04-04 15:27
Sorry, sorry, guys. Was really very busy with some stuffs. But you guys gonna get the first look tonight. Btw @Subway19 you could start working on the Twitter API part on your local machine if you want. Except that part everything else are pretty much done. Will share within an or two hours after I reach home. On my way :P

**Comment by Ryuno-Ki** [comment] 2016-04-04 19:55
@anistuhin commented 4 hours ago:
> Will share within an or two hours after I reach home.

*scnr*

**Comment by anistuhin** [comment] 2016-04-04 22:16
Here is the repo: https://github.com/anistuhin/mozcoffee

**Comment by anistuhin** [comment] 2016-04-06 08:47
Guys, who's coordinating this one?? I mean, I need to know the source of those events in the events slider. From where we are going to collect them?? Will them be automated or just static images and title with links??

**Comment by elioqoshi** [comment] 2016-04-09 13:23
@yofiesetiawan ping

**Comment by yofiesetiawan** [comment] 2016-04-09 13:39
Hi,

It would be great if we can get the data of events from https://reps.mozilla.org/events/#/period/future/

And pictures from flickr with #mozcoffee hashtag..

**Comment by anistuhin** [comment] 2016-04-09 15:18
Well, the event slider shows a picture with the title of that particular event name of that photo, so how are we gonna match that?? If it was just a photo slider then it would be fine.

**Comment by yofiesetiawan** [comment] 2016-04-09 15:27
@anistuhin i think we can use that for photo gallery instead of event name, agree @seeam ?

**Comment by anistuhin** [comment] 2016-04-09 15:31
Yes, we definitely can. On the other hand, we can choose some great events and refer them there so that other who will visit the site can have an idea may be, something like featuring MozCoffee events there with static contents.

**Comment by seeam** [comment] 2016-04-09 15:44
@anistuhin the idea was to feature previous event's blog post. You'll find many blog posts if you simply search on google. I think we cab link to those blog.

**Comment by anistuhin** [comment] 2016-04-09 15:46
yeah, fine. That means we are entering static contents, no need to write any scrapper :) Thanks @seeam

**Comment by Junaed33** [comment] 2016-04-24 15:02
@elioqoshi i'm interested to design mozcoffe website if @seeam's design is not selected finally. Let me know about mozcoffee website update please.

**Comment by yofiesetiawan** [comment] 2016-04-24 17:41
@Junaed33 hi, @seeam design is already final and coded by @anistuhin https://github.com/anistuhin/mozcoffee

**Comment by parag9d** [comment] 2016-04-24 17:54
@yofiesetiawan @anistuhin There are still refinements to be done on the website. It is not loading properly for responsive devices as designed in https://dribbble.com/ParagNandi/projects/364315-MozCoffee. Also, the height of the hero image is to be changed to match the design.

**Comment by anistuhin** [comment] 2016-04-24 18:16
Feel free to change and do a PR :) Having my semester final, I will be quite busy for a week more from now, thanks btw for suggesting :)

**Comment by parag9d** [comment] 2016-04-24 18:19
Same here. End-sem exams starting from tomorrow :(
Let's take it up and complete it after a week maybe...

**Comment by Mte90** [comment] 2016-05-25 09:47
So we need a little focus of the missing step to close this site in a way that for a new contributor is easy to join:

* Improve the responsive https://dribbble.com/ParagNandi/projects/364315-MozCoffee
* Get events from the reps portal (we have to check if a mozcoffee is filterable)
* Twitter widget with #mozcoffee hashtag
* Propose a photo slider and remove the static photo in the big header

Now I have few questions:

* This site will be remain static?
* Create an event how work? I think that on click on that button will have a lightbox that explain that for organize one you need a rep to add in the reps portal

**Comment by elioqoshi** [comment] 2016-05-28 10:05
@tomfarrow can we request hosting for this and a domain?

**Comment by TomFarrow** [comment] 2016-05-28 10:15
@elioqoshi I'm not sure whether this falls under MCWS' scope or Pierros' scope. But, file a request to MCWS, and I can pass it to @ppapadeas if it makes sense to do that.

Either way, yes, somebody can host it. I'll help figure out who :)

Thanks

**Comment by ecwebservices** [comment] 2016-05-28 13:36
I'd host for free until January 2017 that's when my hosting runs out. Just let me know and I can set it up. All that need to be done by others is pointing it.

**Comment by ecwebservices** [comment] 2016-05-28 13:51
Also if I host it I could give @anistuhin FTP access so he can update it whenever.

**Comment by ecwebservices** [comment] 2016-05-28 14:11
Feel free to test my speed http://ecwebservices.xyz because I know now-a-days it is a big issue.

**Comment by karanverma** [comment] 2016-05-28 16:50
when this web will be available ?

**Comment by ecwebservices** [comment] 2016-05-28 18:59
@karanverma Seems like soon to me.

**Comment by lauriiii** [comment] 2016-05-29 20:02
@Mte90 I could help with issues regarding responsiveness. Is there an issue list anywhere? Should I make pull requests to @anistuhin's repo?

**Comment by Mte90** [comment] 2016-05-29 21:20
I read only the previous comments, check on the top @lauriiii

**Comment by karanverma** [comment] 2016-05-30 15:18
Any work for Mozcoffee website and other that can I contribute something ?

**Comment by Slayslot** [comment] 2016-06-03 19:33
Hi, guys. I'm new here and would love to help. Is there any part of implementation left to work on? Also, I saw discussion about hosting being done in the previous comments, I don't know if you guys have already discussed gh-pages, if not you can host this using that. That's what we do for our local community [Mozpacers](http://www.mozpacers.com).

P.S. The final hero image being used was one of the early mozcoffee conducted by Mozpacers, so thank you for that.

**Comment by elioqoshi** [comment] 2016-08-10 16:56
@Slayslot Hey, I just saw this, sorry. Feel free to jump into our next meetings :)
https://github.com/mozilla/OpenDesign/issues/84

**Comment by jonathanKingston** [comment] 2016-09-29 23:59
Moz.coffee became available. I bought it. Let me know if you need any more help / are ready to launch as it would be cool to get this off the ground.

**Comment by jonathanKingston** [comment] 2016-09-30 00:00
Also mozilla.coffee is blocked to being registered however contacting doughnuts the registrar would likely be possible as well.. this is a mozilla property etc.

**Comment by ecwebservices** [comment] 2016-10-04 17:24
Would be good to launch. Looks like it's almost time.

**Comment by ecwebservices** [comment] 2016-12-06 14:06
Seeing if something is going on for this still?

**Comment by elioqoshi** [comment] 2017-01-13 11:34
@nukeador @ppapadeas Do you think there is time and space for this to be used by Participation / Open Innovation whatever?

**Comment by nukeador** [comment] 2017-01-13 12:26
@elioqoshi what the specific ask here for Open Innovation team?

**Comment by hmitsch** [comment] 2017-01-13 12:43
I love moz.coffee

Maybe we could use it on our ParSys initiative?

What's the specific action we need to take? Can you hold on to that URL for
another 6 months and we reevaluate the question then?

**Comment by elioqoshi** [comment] 2017-01-15 10:08
A MozCafe prototype has been created aggregating various MozCafe events. Would there be any interest to host this on infrastructure and integrate it in any way?

**Comment by hmitsch** [comment] 2017-01-16 08:24
Yes!
Can we get together on call in the next few days to discuss next steps? Who
should be on this call? Only Elio and Henrik?

Regards,
  Henrik

**Comment by elioqoshi** [comment] 2017-01-16 10:34
@anistuhin @parag9d @yofiesetiawan are probably better suited but I'd be happy to be part of it as well :)

**Comment by tripad** [comment] 2017-01-18 06:54
Am i late for the party ? 

I am little confused where are we with this. I see a [repo ](http://anistuhin.github.io/mozcoffee/) with a semi finished version and some discussion about hosting it.

I would love to chip in:
- Is the code part done ? 
- I had some ideas around the content as well is the above call scheduled ?
- If you guys need someone to host it, i have a US location VPS available for that

**Comment by jonathanKingston** [comment] 2017-04-04 14:18
This likely would have to be redesigned for the new brand logo if it's going to be an official Mozilla property with the new moz://a protocol design.

However a splash screen with one of the logos and linking to activate.mozilla.community might be a good start.

I will try and find someone who can help.

**Comment by MichaelKohler** [comment] 2017-04-04 14:20
Yes, linking to activate.mozilla.community for now would be great!

**Comment by elioqoshi** [comment] 2017-04-05 09:37
@yofiesetiawan Want to do the redesign?

**Comment by elijahcruz12** [comment] 2017-04-05 15:33
If there is a redesign, I would love to also help with it. I sent a pr a while back to the [repo](http://anistuhin.github.io/mozcoffee/) that contained the code, but just adding a twitter widget. I would love to contribute more to this project though.

**Comment by jonathanKingston** [comment] 2017-04-05 16:23
I briefly spoke to Bradley Cohen from the branding team and he suggested that we wouldn't be able to use the name MozCoffee under the new brand guidelines. He suggested some alternatives but I will follow up with him regarding suggestions.

**Comment by elioqoshi** [comment] 2017-04-05 18:05
True. Mozilla Coffee should be fine however.

**Comment by jonathanKingston** [comment] 2017-04-05 20:58
Mozilla.coffee domain should be able to be purchased by Mozilla if that was
really needed too. It's reserved because Mozilla own it.

**Comment by TomFarrow** [comment] 2017-04-05 21:59
We have a DPML block on mozilla.coffee. WebOps can arrange purchasing via MarkMonitor with very little work/cost.

I'd happily provide advice/resources for hosting this on Mozilla properties. Either MCWS or Participation Systems should be able to resource this, but I'd have to think about scope to decide which is more appropriate. Once you have a working website, getting it online should be pretty easy.

**Comment by elioqoshi** [comment] 2017-04-06 10:07
@elijahcruz12 would appreciate your help here :)

The font Zilla is released on 17th April so that will help. You can use Arvo in the meantime

**Comment by elijahcruz12** [comment] 2017-04-06 15:43
I still have a copy of the original repo, if you want to base it to be similar to the design that was originally picked but use the new design protocol.

**Comment by elijahcruz12** [comment] 2017-04-11 00:00
@elioqoshi should I use the old repo as a base, since it is already an excellent design?

**Comment by elioqoshi** [comment] 2017-04-11 07:16
Sure, whatever you prefer!

**Comment by elijahcruz12** [comment] 2017-04-20 17:29
On the repo, I am adding stuff slowly, but can use some insight to what is wanted for the look of the site.

So far I have it [Here](http://elijahcruz.me/mozcoffee/). It is on GH pages, but on my domain.

I just would like to get input about how I should design it further as well as get others to edit the design as well.

**Comment by elioqoshi** [comment] 2017-04-23 13:45
That's a good start! There is a lot of things which doesn't fit with Mozilla's new style guide though, so you might want to check it out:

https://internethealthreport.org/v01/

This is how the logo could look like

![mozilla coffee logo](https://cloud.githubusercontent.com/assets/5436686/25314022/ab09df24-283b-11e7-9a52-59bb543b16f5.jpg)

**Comment by elijahcruz12** [comment] 2017-04-24 15:18
That is a really amazing logo. I will implement that soon.

**Comment by elijahcruz12** [comment] 2017-04-28 17:11
Updating. I have implemented that logo on the bottom of the page, and I am working on changing the site to fit the style guide. I will also add the logo to the top.

**Comment by barrosgeraldo** [comment] 2017-07-16 18:29
@elijahcruz12, the Mozilla branding is here: https://mozilla.ninja.

**Comment by elijahcruz12** [comment] 2017-08-10 22:57
Sorry I was gone forever. I will be starting doing this when I can. For the past long while I have not had wifi at home, thus have not been able to work on this. The thing is, I want to do this, so I will.

**Closed** 2017-11-13 09:18 UTC
Labels: Frontend Dev needed, Staff Support needed, UI Design needed
